# -*- coding: utf-8 -*-
"""Yolov10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ivxAK5QHhqw2GXCb5Uk6Pr_Kl3HBq3Ch
"""

!pip install roboflow
!pip install ultralytics
from roboflow import Roboflow
rf = Roboflow(api_key="RQ2idiqegaG2AUWvgBgI")
project = rf.workspace("pevi").project("pcb-defect-detection-upbty")
version = project.version(3)
dataset = version.download("yolov9")

from ultralytics import YOLO

model = YOLO("yolov10n.pt")

model.train(data= "/content/PCB-Defect-Detection-3/data.yaml", epochs=100, batch=32, imgsz=640, plots=True)